Bring podman updated from https://github.com/redhat-actions/podman-install/blob/main/action.yml to fix issues in build
Signed-off-by: Leonardo Amaral <contato@leonardoamaral.com.br>

diff --git a/.github/workflows/container-build-stable-buildah.yml b/.github/workflows/container-build-stable-buildah.yml
--- a/.github/workflows/container-build-stable-buildah.yml
+++ b/.github/workflows/container-build-stable-buildah.yml
@@ -29,10 +29,39 @@ jobs:
           - linux/arm64
           - linux/arm/v7
     steps:
-    - name: Buildhah prepare
+    - name: Update podman to 5.x
+      if: runner.os == 'Linux'
+      shell: bash
       run: |
-        sudo apt update
-        sudo apt install -y buildah podman
+        ubuntu_version='${{ inputs.ubuntu-version }}'
+        echo "INFO: Using Ubuntu version '${ubuntu_version}' for Kubic repository."
+
+        echo "INFO: Adding Kubic repository..."
+        sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
+        curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic.gpg
+
+        echo "INFO: Updating package list..."
+        sudo apt-get update -qq
+
+        echo "INFO: Installing CRIU dependencies..."
+        sudo apt-get install --allow-unauthenticated -qq -y libprotobuf32t64 python3-protobuf libnet1
+
+        echo "INFO: Installing CRIU manually..."
+        curl -sLO http://archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_3.16.1-2_amd64.deb && sudo dpkg -i criu_3.16.1-2_amd64.deb
+
+        echo "INFO: Installing Podman..."
+        sudo apt-get -qq -y install --allow-unauthenticated podman buildah || {
+          echo "WARN: Primary installation failed. Trying fallback repository..."
+          sudo sh -c "echo 'deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
+          curl -fsSL "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic-fallback.gpg
+          sudo apt-get --allow-insecure-repositories update -qq
+          sudo apt-get --allow-unauthenticated -y install podman buildah
+        }
+
+        sudo usermod --add-subuids 524288-589823 --add-subgids 524288-589823 $(id -nu)
+
+        echo "INFO: Podman installation complete."
+        podman version
 
     - name: Checkout code
       uses: actions/checkout@v4
@@ -122,10 +151,39 @@ jobs:
       packages: write
     needs: build
     steps:
-    - name: Buildhah prepare
+    - name: Update podman to 5.x
+      if: runner.os == 'Linux'
+      shell: bash
       run: |
-        sudo apt update
-        sudo apt install -y podman
+        ubuntu_version='${{ inputs.ubuntu-version }}'
+        echo "INFO: Using Ubuntu version '${ubuntu_version}' for Kubic repository."
+
+        echo "INFO: Adding Kubic repository..."
+        sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
+        curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic.gpg
+
+        echo "INFO: Updating package list..."
+        sudo apt-get update -qq
+
+        echo "INFO: Installing CRIU dependencies..."
+        sudo apt-get install --allow-unauthenticated -qq -y libprotobuf32t64 python3-protobuf libnet1
+
+        echo "INFO: Installing CRIU manually..."
+        curl -sLO http://archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_3.16.1-2_amd64.deb && sudo dpkg -i criu_3.16.1-2_amd64.deb
+
+        echo "INFO: Installing Podman..."
+        sudo apt-get -qq -y install --allow-unauthenticated podman || {
+          echo "WARN: Primary installation failed. Trying fallback repository..."
+          sudo sh -c "echo 'deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
+          curl -fsSL "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic-fallback.gpg
+          sudo apt-get --allow-insecure-repositories update -qq
+          sudo apt-get --allow-unauthenticated -y install podman
+        }
+
+        sudo usermod --add-subuids 524288-589823 --add-subgids 524288-589823 $(id -nu)
+
+        echo "INFO: Podman installation complete."
+        podman version
 
     - name: Download digests
       uses: actions/download-artifact@v4
